### ISSUE TITLE
reactrouter v7 ?

### ISSUE THREAD

**Issue by 4FunAndProfit** [forge42dev/remix-client-cache#13]
Hello, 

Is this library compatible with RR7 ? 

Should we not change package.json and some code?

Thanks a lot for this great work :)

**Comment by AlemTuzlak** [comment]
@4FunAndProfit you can try running the command in this pr to get it running locally on rr7
https://github.com/forge42dev/remix-client-cache/pull/14

**Comment by 4FunAndProfit** [comment]
Thanks a lot @AlemTuzlak !

Will try it this weekend :)

**Comment by 4FunAndProfit** [comment]
@AlemTuzlak , just tried it on my project! seem to work great in RR7 ! 
thanks a lot again, i'm closing this issue :)
