### ISSUE TITLE
Invalidate `normal` cache on `action`?

### ISSUE THREAD

**Issue by THOUSAND-SKY** [forge42dev/remix-client-cache#4]
I used a bunch of `normal` caches to not fetch data that hasn't changed between page changes, but I was expecting an action on the same page to invalidate even the `normal` cache (in `swr` manner).

In essence I was expecting it to be a strategy that behaves like `swr` if `action` is triggered, but otherwise like `normal`.

**Comment by AlemTuzlak** [comment]
I somehow completely missed this. I added a new API that makes this invalidation a single liner called `decacheClientLoader`
