### ISSUE TITLE
Pathless routes having the same cache key as their parent

### ISSUE THREAD

**Issue by ivancea** [forge42dev/remix-client-cache#8]
Example route with a [pathless child](https://remix.run/docs/en/main/file-conventions/routes#nested-layouts-without-nested-urls):
```
/accounts.tsx
/accounts._index.tsx
```

Both have the same cache key. As seen in `useCachedLoaderData()` result:
```
/accounts.tsx:
{ serverData: {…}, deferredServerData: undefined, key: "/accounts", cacheKey: "/accounts", ... }
/accounts._index.tsx:
{ serverData: {…}, deferredServerData: undefined, key: "/accounts", cacheKey: "/accounts", ... }
```

This makes the first renders of the child route return wrong data (The data from the parent), leading to potential `X is undefined` errors, between others.

**Comment by HazelDaniel** [comment]
did you export a clientLoader on the index route?

**Comment by ivancea** [comment]
@HazelDaniel Yeah, the same as in the other routes, with `hydrate = true`.

A reproducible example:

```tsx
/// routes/test.tsx

import { json } from "@remix-run/node";
import { ClientLoaderFunctionArgs, Outlet } from "@remix-run/react";
import { cacheClientLoader, useCachedLoaderData } from "remix-client-cache";

export const clientLoader = (args: ClientLoaderFunctionArgs) =>
  cacheClientLoader(args);

clientLoader.hydrate = true;

export async function loader() {
  return json({ parent: await Promise.resolve(1) });
}

export default function Index() {
  const a = useCachedLoaderData<typeof loader>();
  console.log("Parent: ", a);

  return <Outlet />;
}
```

```tsx
/// routes/test._index.tsx

import { json } from "@remix-run/node";
import { ClientLoaderFunctionArgs } from "@remix-run/react";
import { cacheClientLoader, useCachedLoaderData } from "remix-client-cache";

export const clientLoader = (args: ClientLoaderFunctionArgs) =>
  cacheClientLoader(args);

clientLoader.hydrate = true;

export async function loader() {
  return json({ child: await Promise.resolve(5) });
}

export default function Index() {
  const a = useCachedLoaderData<typeof loader>();
  console.log("Child: ", a);

  return null;
}
```

First execution:
![imagen](https://github.com/user-attachments/assets/fa1fd6dc-fe70-485f-bbd3-5261d87d9979)

On navigate, when there's a cache stored:
![imagen](https://github.com/user-attachments/assets/b080ddcf-b71c-45bc-986c-121993bea7ed)
(Note that the parent receives the child data here; I had the inverse in another case too)

**Comment by HazelDaniel** [comment]
you can pass in an optional "key" in this part of your code to distinguish the key for each route:
```js
export const clientLoader = (args: ClientLoaderFunctionArgs) =>
  cacheClientLoader(args, {
   key: "YOUR_PATH_NAME"
  });

```

i'd suggest you use something like [CURRENT_PATH_NAME] + "?index" as key for the index route to excuse the overhead of remembering hard-coded routes.

**Comment by HazelDaniel** [comment]
you can pass in an optional "key" in this part of your code to distinguish the key for each route:
```js
export const clientLoader = (args: ClientLoaderFunctionArgs) =>
  cacheClientLoader(args, {
   key: "YOUR_PATH_NAME"
  });

```

i'd suggest you use something like [CURRENT_PATH_NAME] + "?index" as key for the index route to avoid the overhead of remembering hard-coded route keys.

**Comment by ivancea** [comment]
Ok, didn't know that param.
Luckily, after finding this problem, I got to avoid it by removing the loader, which I didn't really need in the "layout".
I'm keeping this issue here though, as this looks like a nasty bug, which was somewhat hard to spot at first, and is quite easy to fall into it

**Comment by AlemTuzlak** [comment]
@HazelDaniel is completely correct on how to avoid this @ivancea. Unfortunately there is no possible way for me to avoid this because I use the request url to construct the key which has the same url in the case you outlined, hence the key parameter that allows you to define a custom key to go around this limitation in case you need it. I do not have build time info at runtime so I couldn't get the route unique ID and use that as the key and I went with the "sane-est" default. Although thank you for raising the issue and if you are reading this in the future using the key param is the way to do it!
